[03/Jul/2014 11:02:03] INFO [core.utils:12] uploading local AIDR file: Classified_2014-05-balkanfloods_last_100k_tweets-1.csv
[03/Jul/2014 11:02:03] ERROR [django.request:226] Internal Server Error: /download/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/views.py", line 14, in downloadPage
    return utils.generateData(request.FILES.get('data-file'),request.POST.get('app'), "file", cacheKey)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 28, in generateData
    processCSVInput(dataFile, app, cacheKey)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 88, in processCSVInput
    aidr_json.append(writeFile(data, app, cacheKey, offset))
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 186, in writeFile
    outputfile = open("static/output/"+filename, "w")
IOError: [Errno 2] No such file or directory: u'static/output/textclicker20140703110203_1.csv'
[03/Jul/2014 11:07:05] INFO [core.utils:12] uploading local AIDR file: Classified_2014-05-balkanfloods_last_100k_tweets-1.csv
[03/Jul/2014 11:07:06] ERROR [django.request:226] Internal Server Error: /download/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/views.py", line 14, in downloadPage
    return utils.generateData(request.FILES.get('data-file'),request.POST.get('app'), "file", cacheKey)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 29, in generateData
    processCSVInput(dataFile, app, cacheKey)
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 84, in processCSVInput
    aidr_json.append(writeFile(data, app, cacheKey, offset))
  File "/media/Storage/Active/SpatialCollective/MicroFilters/core/utils.py", line 183, in writeFile
    outputfile = open("static/output/"+filename, "w")
IOError: [Errno 2] No such file or directory: u'static/output/textclicker20140703110706_1.csv'
